name: Deploy

on:
  pull_request:
    # Optionally configure to run only for specific files. For example:
    # paths:
    # - "website/**"

jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Add any build steps here. For example:
      # - run: npm ci && npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "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"
          firebaseServiceAccount: "firebase-adminsdk-ih7c2@ang-blog-9ab69.iam.gserviceaccount.com"
          expires: 30d
          projectId: ang-blog-9ab69
